version: '3.8'

services:

  client:
    build: 
      context: ./client
      dockerfile: Dockerfile.dev
    ports: 
      - "3000:3000"
    volumes:  
      - ./client/src:/usr/app/src
    tty: true 
    stdin_open: true
    environment:
      CLIENT_PORT: "3000"
      CHOKIDAR_USEPOLLING: "true"