const currencyMapping = {
    'BGN': 'лв',
    'BRL': 'R$',
    'BDT': '৳',
    'BTC': '₿',
    'CHF': 'CHF',
    'CNY_1': '¥',
    'CNY_2': '元',
    'CZK': 'Kč',
    'DKK': 'kr',
    'EUR': '€',
    'ETH': 'Ξ',
    'GBP': '£',
    'GEL': '₾',
    'HKD': 'HK$',
    'HRK': 'kn',
    'HUF': 'ft',
    'IND': 'Rp',
    'INR': '₹',
    'ILS': '₪',
    'JPY': '¥',
    'KES': 'Ksh',
    'KRW': '₩',
    'LKR': 'Rs',
    'LTC': 'Ł',
    'MAD': '.د.م', 
    'MYR': 'RM',
    'NOK': 'kr',
    'NGN': '₦',
    'PHP': '₱',
    'PKR': 'Rs',
    'PLN': 'zł',
    'RUB': '₽',
    'RON': 'lei',
    'SEK': 'kr',
    'THB': '฿',
    'TRY': '₺',
    'UAE': 'د.إ', 
    'UAH': '₴',
    'US': '$',
    'VND': '₫',
    'XNB': '₿',
    'XRP': 'XRP',
    'XMR': 'ɱ',
    'ZAR': 'R',
};

export default currencyMapping;